# Generated by Django 5.2.5 on 2025-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Поставщик", "verbose_name_plural": "Поставщики"},
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(verbose_name="Дата выхода продукта на рынок"),
        ),
    ]
